name = "Queryverse"
uuid = "612083be-0b0f-5412-89c1-4e7c75506a58"
version = "0.6.3-DEV"

[deps]
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataTables = "743a1d0a-8ebc-4f23-814b-50d006366bc6"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
DataVoyager = "5721bf48-af8e-5845-8445-c9e18126e773"
ExcelFiles = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
FeatherFiles = "b675d258-116a-5741-b937-b79f054b0542"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
ParquetFiles = "46a55296-af5a-53b0-aaa0-97023b66127f"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
CSVFiles = "1"
DataFrames = "0.20, 0.21, 0.22"
DataTables = "0.1"
DataValues = "0.4.4"
DataVoyager = "0.3, 1"
ExcelFiles = "1"
FeatherFiles = "0.8"
FileIO = "1"
IterableTables = "1"
ParquetFiles = "0.2"
Query = "0.12, 1.0"
Reexport = "0.2, 1"
StatFiles = "0.8"
VegaLite = "1, 2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
